[package]
name = "rust_lib_otaupdater"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
jni = "0.22.4"
obfstr = "0.4.4"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

# [profile.release]
# opt-level = 's'     # Enable all optimizations
# lto = 'thin'        # Enable link-time optimization (thin is safer for FFI)
# codegen-units = 1   # Reduce number of codegen units to increase optimizations
# panic = 'abort'     # Abort on panic
# strip = false       # DO NOT strip - FFI requires symbols
# debug = false       # Disable debug info
