// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Update Button Status
enum UpdateButtStatus {
  /// Idle, e.g. First time starting the app,
  /// No Update Available
  noUpdate,

  /// Update Available, but not downloaded yet
  updateAvailable,

  /// Downloading Update
  downloading,

  /// Update Downloaded and ready to install
  readyToInstall,
}
